spring:
  application:
    name: "gateway-server"
  config:
    import: "optional:configserver:http://localhost:8071"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*" #actuator will expose all the endpoints
  info: # espose the ms info
    env:
      enabled: true
  endpoint:
    gateway:
      enabled: true


# info shown at eureka dashboard
info:
  app:
    name: ${spring.application.name}
    description: "Fdifrison Gateway Server ms"
    version: 0.0.5

