spring:
  application:
    name: "gateway-server"
  config:
    import: "optional:configserver:http://localhost:8071"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true # service name in lowercase
      httpclient: # will be applied to all requests passing through the gateway
        connect-timeout: 1000
        response-timeout: 10s
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s
  security:
    oauth2:
      resourceserver:
        jwt:
          # uri to jet keycloak public certificate
          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs" # openid-config "jwks_uri"

management:
  endpoints:
    web:
      exposure:
        include: "*" #actuator will expose all the endpoints
  info: # espose the ms info
    env:
      enabled: true
  endpoint:
    gateway:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

# configuration for circuitbreaker filter
resilience4j:
  circuitbreaker:
    configs:
      default: # name of the circuitbreaker if we need to differentiate the behavior
        sliding-window-size: 10 # how many requests the filter has to monitor at least before taking any decision
        permitted-number-of-calls-in-half-open-state: 2 # allows 2 requests in half-open state
        failure-rate-threshold: 50 # if at least 50% of my requests are failing -> move to open state
        wait-duration-in-open-state:
          seconds: 10



# info shown at eureka dashboard
info:
  app:
    name: ${spring.application.name}
    description: "Fdifrison Gateway Server ms"
    version: 0.0.8


logging:
  level:
    org:
      fdifrison:
        micro:
         gatewayserver: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]" # info inserted at runtime
    # %5p leaves some space for openTelemetry to add a description
