spring:
  application:
    name: "service-discovery-agent"
  config:
    import: "optional:configserver:http://localhost:8071/" # config-server port


# We need this to enable health-checks during docker-compose up (readiness/liveness)
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"