server:
  port: 8090
spring:
  application:
    name: "loans"
  profiles:
    active: "default"
  config:
    import: "optional:configserver:http://localhost:8071"
  datasource:
    url: jdbc:mysql://localhost:3307/loans-db
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: "*" #actuator will expose all the endpoints
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info: # espose the ms info
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

endpoints:
  shutdown:
    enabled: true


eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

# info shown at eureka dashboard
info:
  app:
    name: ${spring.application.name}
    description: "Fdifrison Bank Loans ms"
    version: 0.0.5

logging:
  level:
    org:
      fdifrison:
        micro:
          loans: DEBUG