services:
  network-deploy-service:
    networks:
      - fdifrisonNet

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_RABBITMQ_HOST: "rabbit" #override local ms property instead of localhost

  microservice-config-server-config:
    extends:
      service: microservice-base-config
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8071/"
      SPRING_PROFILES_ACTIVE: "qa"