services:
  accounts-db:
    container_name: accounts-db
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: accounts-db
    extends:
      file: common-config.yml
      service: microservice-db-config

  loans-db:
    container_name: loans-db
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: loans-db
    extends:
      file: common-config.yml
      service: microservice-db-config

  cards-db:
    container_name: cards-db
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: cards-db
    extends:
      file: common-config.yml
      service: microservice-db-config

  config-server:
    image: fdifrison/config-server:0.0.5
    container_name: config-server-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1" # need curl installed on image
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      SPRING_APPLICATION_NAME: "config-server"
    extends:
      file: common-config.yml
      service: microservice-base-config

  service-discovery-agent:
    image: fdifrison/config-server:0.0.5
    container_name: config-server-ms
    ports:
      - "8070:8070"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1" # need curl installed on image
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "service-discovery-agent"
    extends:
      file: common-config.yml
      service: microservice-config-server-config

  accounts:
    image: fdifrison/accounts:0.0.5
    container_name: accounts-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accounts-db:3306/accounts-db"
    depends_on:
      accounts-db:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-eureka-config


  loans:
    image: fdifrison/loans:0.0.5
    container_name: loans-ms
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loans-db:3306/loans-db"
    depends_on:
      loans-db:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-eureka-config


  cards:
    image: fdifrison/cards:0.0.5
    container_name: cards-ms
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cards-db:3306/cards-db"
    depends_on:
      cards-db:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  fdifrisonNet:
    driver: "bridge"