services:
  network-deploy-service:
    networks:
      - fdifrisonNet

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      JAVA_TOOL_OPTIONS: "-javaagent:/app/libs/opentelemetry-javaagent-1.32.0.jar" # we have defined the dependency inside the pom
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4317 # opentelemetry will send data to tempo
      OTEL_METRICS_EXPORTER: none # we use prometheus

  microservice-config-server-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8071/
      SPRING_PROFILES_ACTIVE: "default"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  microservice-eureka-config:
    extends:
      service: microservice-config-server-config
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery-agent:8070/eureka/
