services:
  rabbit:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  config-server:
    image: fdifrison/config-server:0.0.1
    container_name: config-server-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - fdifrisonNet
  accounts:
    image: fdifrison/accounts:0.0.2
    container_name: accounts-ms
    ports:
      - "8080:8080"
    depends_on:
      config-server:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - fdifrisonNet
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8071" # remove optional, we want it to fail if it cannot connect to config-server
      SPRING_PROFILES_ACTIVE: "default"
  loans:
    image: fdifrison/loans:0.0.2
    container_name: loans-ms
    ports:
      - "8090:8090"
    depends_on:
      config-server:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - fdifrisonNet
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8071" # remove optional, we want it to fail if it cannot connect to config-server
      SPRING_PROFILES_ACTIVE: "default"
  cards:
    image: fdifrison/cards:0.0.2
    container_name: cards-ms
    ports:
      - "9000:9000"
    depends_on:
      config-server:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - fdifrisonNet
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8071" # remove optional, we want it to fail if it cannot connect to config-server
      SPRING_PROFILES_ACTIVE: "default"
networks:
  fdifrisonNet:
    driver: "bridge"