server:
  port: 9010

spring:
  application:
    name: "message"
  cloud:
    function:
      definition: email|sms
    stream:
      bindings:
        email-sms-in-0: # binding name following default naming convention (functionsName-input-startingPosition)
          destination: send-communication # name of the queue in RabbitMQ
          group: ${spring.application.name} # to avoid random generated name by RabbitMQ
        email-sms-out-0:
          destination: communication-sent # spring clouds functions knows
          # that it can send the output of the email|sms function from this queue
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10
