spring:
  application:
    name: "config-server"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/fdifrison/SpringBootMicro-config.git"
          default-label: "main" # branch we are pointing to
          timeout: 5
          clone-on-start: true # try to clone the repo each time
          force-pull: true # override the local changes, reading always from remote
          username: "ing.giovanni.frison@gmail.com"
          password: ${GITHUB_TOKEN} # access token for gitHub repo

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true


server:
  port: 8071
