spring:
  application:
    name: "config-server"
  profiles:
    active: "default"
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/fdifrison/SpringBootMicro-config.git"
          default-label: "main" # branch we are pointing to
          timeout: 5
          clone-on-start: true # try to clone the repo each time
          force-pull: true # override the local changes, reading always from remote
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}


server:
  port: 8071

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"